hotfolder:
    path: @components.integration.collection.csv.hotfolder@
spring:
    application:
        name: ou-integration-collection-csv
    cloud:
        stream:
            bindings:
                output:
                    destination: mdm-readings-csv-input
                    producer:
                        headerMode: raw
            kafka:
                binder:
                    brokers: 192.168.65.111:1026
                    zkNodes: 192.168.65.111:2375
server:
    port: @components.integration.collection.csv.port@