hotfolder:
    path: @components.integration.collection.csv.hotfolder@
spring:
    application:
        name: ou-integration-collection-csv
    kafka:
      bootstrap-servers: 192.168.65.111:1026
    cloud:
        stream:
            bindings:
                output:
                    destination: mdm-readings-csv-input
                    producer:
                        headerMode: raw
            kafka:
                bootstrap-servers: 192.168.65.111:1026
server:
    port: @components.integration.collection.csv.port@