endpoints:
  health:
    enabled: true
application:
    hotfolder:
        path: @components.integration.collection.csv.hotfolder@
    kafka:
      topic: mdm-readings-csv-input
spring:
    kafka:
        bootstrap-servers: @kafka.bootstrap.servers@
    application:
        name: ou-integration-collection-csv
server:
    port: @components.integration.collection.csv.port@