server:
  port: @components.core.appservices.port@

application:
  properties:
    debug: true
spring:
  kafka:
    bootstrap-servers: @kafka.bootstrap.servers@
    consumer:
      group-id: appServices
      auto-offset: earliest
  profiles:
    active: @profile.id@
---
spring:
  profiles: cloud
  datasource:
    url: @database.connection.core.url@
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
---
spring:
  profiles: dev
  datasource:
    url: @database.connection.core.url@
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
---
spring:
  profiles: local
  h2:
    console:
      enabled: @h2.console.enabled@