server:
  port: @components.core.appservices.port@

application:
  properties:
    debug: true
spring:
  profiles:
    active: @profile.id@
---
spring:
  profiles: dev
  datasource:
    url: @database.connection.url@&amp;currentSchema=core
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
---
spring:
  profiles: local
  h2:
    console:
      enabled: @h2.console.enabled@