application:
  name: openutilities-processing-guiding
spark:
  cassandra:
    connection:
      host: @spark.cassandra.connection.host@
      port: @spark.cassandra.connection.port@
  executor:
    memory: 2g
  streaming:
    batch:
      duration: 5000
kafka:
  bootstrap:
    servers: @kafka.bootstrap.servers@
  topic:
    name: ou-readings-input
hazelcast:
  hostname: @hazelcast.hostname@